yolo:
  type: "yolov4"
  iou_threshold: 0.5
  score_threshold: 0.005
  max_boxes: 100
  strides: "32,16,8"
  anchors: "12,16 19,36 40,28 36,75 76,55 72,146 142,110 192,243 459,401"
  mask: "6,7,8 3,4,5 0,1,2"
  name_path: "./data/pascal_voc/voc.name"

train:
  label: "voc_yolov4_NM_LS_CIoU_FL"
  anno_path: "./data/pascal_voc/train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  batch_size: 2
  init_weight_path: "./ckpts/yolov4.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mosaic: false
  label_smoothing: true
  normal_method: true

  ignore_threshold: 0.5

test:
  anno_path: "./data/pascal_voc/test.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: ""